name: scorevault
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/user_info.png
    - assets/catan.jpg
    - assets/7wonders.jpg
    - assets/burraco.jpg
    - assets/lostcities.jpg
